services:
  purrsonal-db:
    container_name: purrsonal-db
    image: postgres:17-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  init-db:
    container_name: init-db
    build:
      context: ./db/
    depends_on:
      purrsonal-db:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      TARGET_CONTAINER: ${CONTAINER_NAME}
      PURRSONAL_DB: ${PURRSONAL_DB_NAME}
      PURRSONAL_USER: ${PURRSONAL_USER}
      PURRSONAL_PASSWORD: ${PURRSONAL_PASSWORD}

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      purrsonal-db:
        condition: service_healthy
    environment:
      PURRSONAL_DB_HOST: purrsonal-db
      PURRSONAL_DB_PORT: ${POSTGRES_PORT}
      PURRSONAL_DB_NAME: ${PURRSONAL_DB_NAME}
      PURRSONAL_DB_USER: ${PURRSONAL_USER}
      PURRSONAL_DB_PASSWORD: ${PURRSONAL_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev
      PURRSONAL_DB_DRIVER: org.postgresql.Driver
      PURRSONAL_DB_DIALECT: org.postgresql.Dialect
    ports:
      - 8080:8080

  ui:
    container_name: ui
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    environment:
      VITE_API_URL: http://localhost:8080/api

volumes:
  pgdata: