services:
  purrsonal-db:
    container_name: purrsonal-db
    image: postgres:17-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  init-db:
    container_name: init-db
    build:
      context: ./db/
    depends_on:
      purrsonal-db:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      TARGET_CONTAINER: ${CONTAINER_NAME}
      PURRSONAL_DB: ${PURRSONAL_DB_NAME}
      PURRSONAL_USER: ${PURRSONAL_USER}
      PURRSONAL_PASSWORD: ${PURRSONAL_PASSWORD}

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      purrsonal-db:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      PURRSONAL_DB_HOST: purrsonal-db
      PURRSONAL_DB_PORT: ${POSTGRES_PORT}
      PURRSONAL_DB_NAME: ${PURRSONAL_DB_NAME}
      PURRSONAL_DB_USER: ${PURRSONAL_USER}
      PURRSONAL_DB_PASSWORD: ${PURRSONAL_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev
      PURRSONAL_DB_DRIVER: org.postgresql.Driver
      PURRSONAL_DB_DIALECT: org.postgresql.Dialect
      JWT_SECRET: ${JWT_SECRET}
      MINIO_USER: ${MINIO_USER}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
      MINIO_HOST: ${MINIO_HOST}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_BUCKET: ${MINIO_BUCKET}
    ports:
      - 8080:8080

  ui:
    container_name: ui
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    environment:
      VITE_API_URL: http://localhost:8080/api

  minio:
    image: quay.io/minio/minio:RELEASE.2025-07-23T15-54-02Z
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/ready || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  minio_data: