spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/purrsonal_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  profiles:
    active: dev
