spring:
  datasource:
    url: jdbc:postgresql://${PURRSONAL_DB_HOST}:${POSTGRES_DB_PORT}/${PURRSONAL_DB_NAME}
    username: ${PURRSONAL_DB_USER}
    password: ${PURRSONAL_DB_PASSWORD}
    driverClassName: ${PURRSONAL_DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
